services:
      #nginx
       web:
         image: nginx:latest
         ports:
           - "8040:80"
       app:
         build:
           dockerfile: ./php/Dockerfile
  #php

  #mysql

  #redis


